/* Generated by AN DISI Unibo */ 
package it.unibo.ioport

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Ioport ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		 
		        var SensorOccupied = false 
		        lateinit var Adapter: ioport.IOPortWsAdapter
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outblue("$name | avvio attore IOPort")
						 Adapter = ioport.IOPortWsAdapter(myself, 7070)  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="acceptEvents", cond=doswitch() )
				}	 
				state("acceptEvents") { //this:State
					action { //it:State
						CommUtils.outblue("$name | in attesa di eventi...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="handleButton",cond=whenDispatch("button_pushed"))
					transition(edgeName="t01",targetState="handleContainerMock",cond=whenDispatch("containerSensed"))
					transition(edgeName="t02",targetState="handleOutOfServiceMock",cond=whenDispatch("outOfService"))
					transition(edgeName="t03",targetState="handleCoreHoldUpdate",cond=whenDispatch("updateHoldDisplay"))
					transition(edgeName="t04",targetState="handleCoreWorkingState",cond=whenDispatch("updateWorkingState"))
					transition(edgeName="t05",targetState="handleLedUpdate",cond=whenDispatch("led"))
				}	 
				state("handleButton") { //this:State
					action { //it:State
						CommUtils.outblue("$name | Pressione pulsante ricevuta dalla GUI")
						 var IoportStateStr = if (SensorOccupied) "true" else "false"  
						request("loadrequest", "loadrequest($IoportStateStr)" ,"cargoservice" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t16",targetState="handleEngaged",cond=whenReply("engaged"))
					transition(edgeName="t17",targetState="handleReject",cond=whenReply("reject"))
					transition(edgeName="t18",targetState="handleRetryLater",cond=whenReply("retrylater"))
				}	 
				state("handleEngaged") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("engaged(RESERVED_SLOT,HOLD_STATE)"), Term.createTerm("engaged(RESERVED_SLOT,HOLD_STATE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 
								                var ReservedSlot = payloadArg(0)
								                var HoldState = payloadArg(1)
								                var StateStr = "'ENGAGED'"
								                var MsgStr = "'Slot " + ReservedSlot + " Riservato'"
								                Adapter.updateHoldStatus(StateStr, HoldState, MsgStr)
								CommUtils.outblue("$name | Risposta engaged da parte di cargoservice: $StateStr, $HoldState, $MsgStr")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="acceptEvents", cond=doswitch() )
				}	 
				state("handleReject") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("reject(HOLD_STATE)"), Term.createTerm("reject(HOLD_STATE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 
								                var HoldState = payloadArg(0) 
								                var StateStr = "'REJECTED'"
								                var MsgStr = "'stiva piena'"
								                Adapter.updateHoldStatus(StateStr, HoldState, MsgStr)
								CommUtils.outblue("$name | Risposta reject da parte di cargoservice: $StateStr, $HoldState, $MsgStr")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="acceptEvents", cond=doswitch() )
				}	 
				state("handleRetryLater") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("retrylater(CAUSE,HOLD_STATE)"), Term.createTerm("retrylater(CAUSE,HOLD_STATE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 
								                var Cause = payloadArg(0)
								                var HoldState = payloadArg(1)
								                var StateStr = "'RETRY LATER'"
								                var CauseStr = "'" + Cause + "'"
								                Adapter.updateHoldStatus(StateStr, HoldState, CauseStr)
								CommUtils.outblue("$name | Risposta retrylater da parte di cargoservice: $StateStr, $HoldState, $CauseStr")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="acceptEvents", cond=doswitch() )
				}	 
				state("handleCoreHoldUpdate") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("updateHoldDisplay(STATE,HOLD_STATE,MSG)"), Term.createTerm("updateHoldDisplay(STATE,HOLD_STATE,MSG)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 Adapter.updateHoldStatus(payloadArg(0), payloadArg(1), payloadArg(2))  
								CommUtils.outblue("$name | Richiesto aggiornamento del display")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="acceptEvents", cond=doswitch() )
				}	 
				state("handleCoreWorkingState") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("updateWorkingState(STATE)"), Term.createTerm("updateWorkingState(STATE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 Adapter.updateWorkingState(payloadArg(0))  
								CommUtils.outblue("$name | Richiesto aggiornamento del working state")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="acceptEvents", cond=doswitch() )
				}	 
				state("handleLedUpdate") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("led(STATE)"), Term.createTerm("led(STATE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 Adapter.updateLed(payloadArg(0))  
								CommUtils.outyellow("$name | Richiesto aggiornamento del led")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="acceptEvents", cond=doswitch() )
				}	 
				state("handleContainerMock") { //this:State
					action { //it:State
						CommUtils.outred("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						 
						        	var SensorVal = currentMsg.msgContent()
						        	SensorOccupied = SensorVal.toBoolean()
						CommUtils.outgreen("$name | Variazione sensore container: $SensorOccupied")
						if(  SensorOccupied  
						 ){forward("containerSensed", "containerSensed(true)" ,"cargoservice" ) 
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="acceptEvents", cond=doswitch() )
				}	 
				state("handleOutOfServiceMock") { //this:State
					action { //it:State
						CommUtils.outred("$name | Simulazione errore del sensore")
						forward("outOfService", "outOfService(sensor_fault)" ,"cargoservice" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="acceptEvents", cond=doswitch() )
				}	 
			}
		}
} 
