/* Generated by AN DISI Unibo */ 
package it.unibo.cargorobot

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Cargorobot ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		val h = cargoservice.Hold()
		
		        var Slot     = 0
		        var X        = 0      // coordinate dello slot finale 
		        var Y        = 0
		        var StepTime = 345
		
		        val MaxHomeAttempts = 3          // tentativi massimi di rientro in HOME
		
		        var Failed       = false         // true se una tappa fallisce
		        var FailCause    = "fail_RobotSmart26"
		        var HomeAttempts = 0
		        var NearHome     = false         // true se manca solo l'ultimo passo per casa
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						
						    		var XHOME = h.getHomeX()
						    		var YHOME = h.getHomeY()
						CommUtils.outblue("$name | starting: mind set at HOME (robot assumed physically at HOME, facing down)")
						forward("setplanbuildelay", "value(0)" ,"robotsmart" ) 
						forward("setrobotstate", "setpos($XHOME,$YHOME,down)" ,"robotsmart" ) 
						delay(1000) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("idle") { //this:State
					action { //it:State
						CommUtils.outblue("$name | waiting for a container...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="extractRequest",cond=whenRequest("transportContainer"))
				}	 
				state("extractRequest") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("transportContainer(SLOT,TARGETX,TARGETY)"), Term.createTerm("transportContainer(SLOT,TARGETX,TARGETY)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
								                Slot         = payloadArg(0).toInt()
								                X            = payloadArg(1).toInt()
								                Y            = payloadArg(2).toInt()
								                Failed       = false
								                FailCause    = "fail_RobotSmart26"
								                HomeAttempts = 0
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="moveIOPort", cond=doswitch() )
				}	 
				state("moveIOPort") { //this:State
					action { //it:State
						
						    		var XIOP = h.getIOPortX()
						    		var YIOP = h.getIOPortY()
						CommUtils.outblue("$name | moving to IOPort ($XIOP, $YIOP)")
						request("moverobot", "moverobot($XIOP,$YIOP,$StepTime)" ,"robotsmart" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_moveIOPort", 
				 	 					  scope, context!!, "local_tout_"+name+"_moveIOPort", 30000.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t11",targetState="moveTimeout",cond=whenTimeout("local_tout_"+name+"_moveIOPort"))   
					transition(edgeName="t12",targetState="collectContainer",cond=whenReply("moverobotdone"))
					transition(edgeName="t13",targetState="legFailed",cond=whenReply("moverobotfailed"))
				}	 
				state("collectContainer") { //this:State
					action { //it:State
						CommUtils.outblue("$name | collecting container...")
						delay(2000) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="moveSlot5", cond=doswitch() )
				}	 
				state("moveSlot5") { //this:State
					action { //it:State
						
						    		var X5 = h.getMarkerX()
						    		var Y5 = h.getMarkerY()
						CommUtils.outblue("$name | moving to slot5 ($X5, $Y5)")
						request("moverobot", "moverobot($X5,$Y5,$StepTime)" ,"robotsmart" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_moveSlot5", 
				 	 					  scope, context!!, "local_tout_"+name+"_moveSlot5", 30000.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t24",targetState="moveTimeout",cond=whenTimeout("local_tout_"+name+"_moveSlot5"))   
					transition(edgeName="t25",targetState="marking",cond=whenReply("moverobotdone"))
					transition(edgeName="t26",targetState="legFailed",cond=whenReply("moverobotfailed"))
				}	 
				state("marking") { //this:State
					action { //it:State
						CommUtils.outblue("$name | marker working...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_marking", 
				 	 					  scope, context!!, "local_tout_"+name+"_marking", 5000.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t37",targetState="moveFinalSlot",cond=whenTimeout("local_tout_"+name+"_marking"))   
				}	 
				state("moveFinalSlot") { //this:State
					action { //it:State
						CommUtils.outblue("$name | moving to final slot ($X, $Y)")
						request("moverobot", "moverobot($X,$Y,$StepTime)" ,"robotsmart" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_moveFinalSlot", 
				 	 					  scope, context!!, "local_tout_"+name+"_moveFinalSlot", 30000.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t48",targetState="moveTimeout",cond=whenTimeout("local_tout_"+name+"_moveFinalSlot"))   
					transition(edgeName="t49",targetState="depositContainer",cond=whenReply("moverobotdone"))
					transition(edgeName="t410",targetState="legFailed",cond=whenReply("moverobotfailed"))
				}	 
				state("depositContainer") { //this:State
					action { //it:State
						CommUtils.outblue("$name | depositing container...")
						delay(2000) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="startHoming", cond=doswitch() )
				}	 
				state("legFailed") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("moverobotfailed(PLANDONE,PLANTODO)"), Term.createTerm("moverobotfailed(PLANDONE,PLANTODO)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outred("$name | tappa fallita! PLANDONE=${payloadArg(0)} PLANTODO=${payloadArg(1)}")
						}
						 Failed = true  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="startHoming", cond=doswitch() )
				}	 
				state("moveTimeout") { //this:State
					action { //it:State
						CommUtils.outred("$name | nessuna risposta da robotsmart entro 30s")
						 Failed = true  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="finishKo", cond=doswitch() )
				}	 
				state("startHoming") { //this:State
					action { //it:State
						 HomeAttempts = 0  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="goHome", cond=doswitch() )
				}	 
				state("goHome") { //this:State
					action { //it:State
						
						    		HomeAttempts++
						    		var XHOME = h.getHomeX()
						    		var YHOME = h.getHomeY()
						CommUtils.outblue("$name | going back home (tentativo $HomeAttempts di $MaxHomeAttempts)")
						request("moverobot", "moverobot($XHOME,$YHOME,$StepTime)" ,"robotsmart" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_goHome", 
				 	 					  scope, context!!, "local_tout_"+name+"_goHome", 30000.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t511",targetState="moveTimeout",cond=whenTimeout("local_tout_"+name+"_goHome"))   
					transition(edgeName="t512",targetState="tuneHome",cond=whenReply("moverobotdone"))
					transition(edgeName="t513",targetState="homeMoveFailed",cond=whenReply("moverobotfailed"))
				}	 
				state("homeMoveFailed") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("moverobotfailed(PLANDONE,PLANTODO)"), Term.createTerm("moverobotfailed(PLANDONE,PLANTODO)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
								                val Todo = payloadArg(1).filter { c -> c.isLetter() }
								                NearHome = (Todo == "w" || Todo == "")
								CommUtils.outred("$name | rientro in HOME fallito: PLANDONE=${payloadArg(0)} PLANTODO=${payloadArg(1)} -> quasi a casa: $NearHome")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="tuneHome", cond=doswitchGuarded({ NearHome  
					}) )
					transition( edgeName="goto",targetState="retryHome", cond=doswitchGuarded({! ( NearHome  
					) }) )
				}	 
				state("retryHome") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name | lontano da HOME, ritento il rientro")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="goHome", cond=doswitchGuarded({ HomeAttempts < MaxHomeAttempts  
					}) )
					transition( edgeName="goto",targetState="homeGiveUp", cond=doswitchGuarded({! ( HomeAttempts < MaxHomeAttempts  
					) }) )
				}	 
				state("homeGiveUp") { //this:State
					action { //it:State
						CommUtils.outred("$name | impossibile rientrare in HOME dopo $MaxHomeAttempts tentativi")
						 Failed = true  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="finishKo", cond=doswitch() )
				}	 
				state("tuneHome") { //this:State
					action { //it:State
						CommUtils.outblue("$name | tuning at home...")
						request("tuneAtHome", "tuneAtHome(end)" ,"robotsmart" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_tuneHome", 
				 	 					  scope, context!!, "local_tout_"+name+"_tuneHome", 20000.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t614",targetState="tuneTimeout",cond=whenTimeout("local_tout_"+name+"_tuneHome"))   
					transition(edgeName="t615",targetState="endHoming",cond=whenReply("tuneDone"))
				}	 
				state("tuneTimeout") { //this:State
					action { //it:State
						CommUtils.outred("$name | tune NON terminato entro 20s")
						 Failed = true  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="finishKo", cond=doswitch() )
				}	 
				state("endHoming") { //this:State
					action { //it:State
						CommUtils.outblue("$name | tune completato, robot riallineato in HOME")
						forward("setrobotstate", "setpos(0,0,down)" ,"robotsmart" ) 
						delay(300) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="finishKo", cond=doswitchGuarded({ Failed  
					}) )
					transition( edgeName="goto",targetState="finishOk", cond=doswitchGuarded({! ( Failed  
					) }) )
				}	 
				state("finishOk") { //this:State
					action { //it:State
						CommUtils.outblue("$name | trasporto finito con successo")
						answer("transportContainer", "transportDone", "transportDone($Slot)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("finishKo") { //this:State
					action { //it:State
						CommUtils.outred("$name | trasporto fallito ($FailCause)")
						answer("transportContainer", "transportFailed", "transportFailed($FailCause)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
			}
		}
} 
