/* Generated by AN DISI Unibo */ 
package it.unibo.cargoservice

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Cargoservice ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		
				var HOLD_FULL = false
				var ENGAGED = false
				var WORKING = true
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name | starts ")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("idle") { //this:State
					action { //it:State
						 var Msg = "cargoservice partito" 
						CommUtils.outmagenta("$name | Sistema in stato IDLE")
						forward("updateHoldDisplay", "updateHoldDisplay($ENGAGED,$HOLD_FULL,$Msg)" ,"ioport" ) 
						forward("updateWorkingState", "updateWorkingState($WORKING)" ,"ioport" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="handleLoadRequest",cond=whenRequest("loadrequest"))
				}	 
				state("handleLoadRequest") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("loadrequest(IOPORT_STATE)"), Term.createTerm("loadrequest(IOPORT_STATE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 
								                var IoportState = payloadArg(0).toBoolean()
								                
								                if (IoportState) {
								                	var Cause = "porta_occupata"
								answer("loadrequest", "retrylater", "retrylater($Cause,$HOLD_FULL)"   )  
								CommUtils.outmagenta("$name | retrylater($Cause, $HOLD_FULL)")
								
								                } else if (HOLD_FULL) {
								answer("loadrequest", "reject", "reject($HOLD_FULL)"   )  
								CommUtils.outmagenta("$name | reject($HOLD_FULL)")
								
								                } else {
								                    HOLD_FULL = true
								                    var Slot = "slot1"
								                    ENGAGED = true
								answer("loadrequest", "engaged", "engaged($Slot,$HOLD_FULL)"   )  
								CommUtils.outmagenta("$name | engaged($Slot, $HOLD_FULL)")
								
								                }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="engagedState", cond=doswitchGuarded({ ENGAGED  
					}) )
					transition( edgeName="goto",targetState="idle", cond=doswitchGuarded({! ( ENGAGED  
					) }) )
				}	 
				state("engagedState") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name | Sistema in stato IDLE")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_engagedState", 
				 	 					  scope, context!!, "local_tout_"+name+"_engagedState", 30000.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t01",targetState="disengagedState",cond=whenTimeout("local_tout_"+name+"_engagedState"))   
					transition(edgeName="t02",targetState="handleBusyRequest",cond=whenRequest("loadrequest"))
				}	 
				state("handleBusyRequest") { //this:State
					action { //it:State
						
									var Cause = "sistema_engaged"
						answer("loadrequest", "retrylater", "retrylater($Cause,$HOLD_FULL)"   )  
						CommUtils.outmagenta("$name | retrylater($Cause, $HOLD_FULL)")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="engagedState", cond=doswitch() )
				}	 
				state("disengagedState") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name | Sistema in stato DISENGAGED")
						 
									ENGAGED = false 
									var Msg = "sistema_disengaged"
						forward("updateHoldDisplay", "updateHoldDisplay($ENGAGED,$HOLD_FULL,$Msg)" ,"ioport" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
			}
		}
} 
