/* Generated by AN DISI Unibo */ 
package it.unibo.cargoservice_ridotto

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Cargoservice_ridotto ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		
				var Slot = "slot1"
				var X = 2
				var Y = 2
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outblack("")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="handleContainer", cond=doswitch() )
				}	 
				state("handleContainer") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name | Container rilevato -> richiesta di movimento del robot")
						request("transportContainer", "transportContainer($Slot,$X,$Y)" ,"cargorobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t09",targetState="handleTransportComplited",cond=whenReply("transportDone"))
					transition(edgeName="t010",targetState="handleTransportFailed",cond=whenReply("transportFailed"))
				}	 
				state("handleTransportComplited") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name | il container è stato prelevato, marcato e depositato nello slot assegnato")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_handleTransportComplited", 
				 	 					  scope, context!!, "local_tout_"+name+"_handleTransportComplited", 5000.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t111",targetState="handleContainer",cond=whenTimeout("local_tout_"+name+"_handleTransportComplited"))   
				}	 
				state("handleTransportFailed") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name | si è verificato un errore durante il trasporto. OUT OF SERVICE!")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
