/* Generated by AN DISI Unibo */ 
package it.unibo.cargoservice

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Cargoservice ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		val h = cargoservice.Hold()
		 
		        var CurrentReservedSlot = -1
		        var CurrentState = "IDLE"
		        var IsOutOfService = false
		        var WaitStartTime = 0L
		        var RemainingTime = 30000L
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name | avvio CargoService Core")
						 var ServiceWorking = "'WORKING'"  
						forward("updateWorkingState", "updateWorkingState($ServiceWorking)" ,"ioport" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("idle") { //this:State
					action { //it:State
						 
						            CurrentState = "IDLE" 
						            var LedOff = "'off'"
						            WaitStartTime = 0L
						            RemainingTime = 30000L
						CommUtils.outmagenta("$name | Sistema in stato IDLE")
						forward("led", "led($LedOff)" ,"ioport" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t09",targetState="handleLoadRequest",cond=whenRequest("loadrequest"))
					transition(edgeName="t010",targetState="handleOutOfService",cond=whenDispatch("outOfService"))
				}	 
				state("handleLoadRequest") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("loadrequest(IOPORT_STATE)"), Term.createTerm("loadrequest(IOPORT_STATE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 
								                var IoportState = payloadArg(0).toBoolean()
								                var CurrentHoldState = h.getHoldStateString()
								                
								                if (IoportState) {
								                    var SystemBusyStr = "'ioport_occupied'" 
								answer("loadrequest", "retrylater", "retrylater($SystemBusyStr,$CurrentHoldState)"   )  
								CommUtils.outmagenta("$name | retrylater($SystemBusyStr, $CurrentHoldState)")
								
								                } else if (h.isFull()) {
								answer("loadrequest", "reject", "reject($CurrentHoldState)"   )  
								CommUtils.outmagenta("$name | reject($CurrentHoldState)")
								
								                } else {
								                    CurrentReservedSlot = h.reserveNextFreeSlot()
								                    if (CurrentReservedSlot != -1) {
								                        CurrentState = "ENGAGED"
								                        CurrentHoldState = h.getHoldStateString()
								                        var LedBlinking = "'blinking'"
								answer("loadrequest", "engaged", "engaged($CurrentReservedSlot,$CurrentHoldState)"   )  
								CommUtils.outmagenta("$name | engaged($CurrentReservedSlot, $CurrentHoldState)")
								forward("led", "led($LedBlinking)" ,"ioport" ) 
								
								                    } else {
								                        var SystemBusyStr = "'system_busy'"
								answer("loadrequest", "retrylater", "retrylater($SystemBusyStr,$CurrentHoldState)"   )  
								CommUtils.outmagenta("$name | retrylater($SystemBusyStr, $CurrentHoldState)")
								
								                    }
								                }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="engagedWaitContainer", cond=doswitchGuarded({ CurrentState == "ENGAGED"  
					}) )
					transition( edgeName="goto",targetState="idle", cond=doswitchGuarded({! ( CurrentState == "ENGAGED"  
					) }) )
				}	 
				state("engagedWaitContainer") { //this:State
					action { //it:State
						 
						            if (WaitStartTime == 0L) {
						                WaitStartTime = System.currentTimeMillis()
						            }
						            var Elapsed = System.currentTimeMillis() - WaitStartTime
						            RemainingTime = 30000L - Elapsed
						            if (RemainingTime <= 0L) RemainingTime = 1L
						CommUtils.outmagenta("$name | In attesa del container (Tempo residuo: ${RemainingTime}ms)...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_engagedWaitContainer", 
				 	 					  scope, context!!, "local_tout_"+name+"_engagedWaitContainer", RemainingTime )  //OCT2023
					}	 	 
					 transition(edgeName="t111",targetState="handleTimeout",cond=whenTimeout("local_tout_"+name+"_engagedWaitContainer"))   
					transition(edgeName="t112",targetState="handleBusyRequest",cond=whenRequest("loadrequest"))
					transition(edgeName="t113",targetState="handleContainer",cond=whenDispatch("containerSensed"))
					transition(edgeName="t114",targetState="handleEngagedOutOfService",cond=whenDispatch("outOfService"))
				}	 
				state("handleBusyRequest") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("loadrequest(IOPORT_STATE)"), Term.createTerm("loadrequest(IOPORT_STATE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 
								                var CurrentHoldState = h.getHoldStateString()
								                var SystemEngagedStr = "'system_engaged'"
								answer("loadrequest", "retrylater", "retrylater($SystemEngagedStr,$CurrentHoldState)"   )  
								CommUtils.outmagenta("$name | retrylater($SystemEngagedStr, $CurrentHoldState)")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="engagedWaitContainer", cond=doswitch() )
				}	 
				state("handleEngagedOutOfService") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name | GUASTO RILEVATO DURANTE ENGAGED!")
						 
						            IsOutOfService = true
						            
						            // Release dello slot che era stato prenotato
						            if (CurrentReservedSlot != -1) {
						                h.releaseSlot(CurrentReservedSlot)
						                CurrentReservedSlot = -1
						            }
						            
						            var CurrentHoldState = h.getHoldStateString()
						            var StateStr = "'OUT_OF_SERVICE'"
						            var MsgStr = "'Guasto sensore durante attesa'"
						            var LedRed = "'red'"
						            var ServiceDown = "'OUT_OF_SERVICE'"
						forward("led", "led($LedRed)" ,"ioport" ) 
						forward("updateWorkingState", "updateWorkingState($ServiceDown)" ,"ioport" ) 
						forward("updateHoldDisplay", "updateHoldDisplay($StateStr,$CurrentHoldState,$MsgStr)" ,"ioport" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="outOfServiceState", cond=doswitch() )
				}	 
				state("handleTimeout") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name | TIMEOUT scaduto! Container non rilevato entro 30s.")
						 
						            if (CurrentReservedSlot != -1) {
						                h.releaseSlot(CurrentReservedSlot)
						                CurrentReservedSlot = -1
						            }
						            var CurrentHoldState = h.getHoldStateString()
						            var StateStr = "'DISENGAGED'"
						            var TimeoutMsgStr = "'Timer scaduto (30s)'"
						forward("updateHoldDisplay", "updateHoldDisplay($StateStr,$CurrentHoldState,$TimeoutMsgStr)" ,"ioport" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("handleContainer") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name | Container rilevato -> aggiornamento slot a OCCUPIED")
						 
						            if (CurrentReservedSlot != -1) {
						                h.setSlotOccupied(CurrentReservedSlot)
						                CurrentReservedSlot = -1
						            }
						            var CurrentHoldState = h.getHoldStateString()
						            var StateStr = "'LOADED'"
						            var LoadedMsgStr = "'Container preso in carico'"
						forward("updateHoldDisplay", "updateHoldDisplay($StateStr,$CurrentHoldState,$LoadedMsgStr)" ,"ioport" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("handleOutOfService") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name | ERRORE SENSORE: Ingresso in Out Of Service")
						 
						            IsOutOfService = true
						            var CurrentHoldState = h.getHoldStateString()
						            var StateStr = "'OUT_OF_SERVICE'"
						            var MsgStr = "'Guasto sensore'"
						            var LedRed = "'red'"
						            var ServiceDown = "'OUT_OF_SERVICE'"
						forward("led", "led($LedRed)" ,"ioport" ) 
						forward("updateWorkingState", "updateWorkingState($ServiceDown)" ,"ioport" ) 
						forward("updateHoldDisplay", "updateHoldDisplay($StateStr,$CurrentHoldState,$MsgStr)" ,"ioport" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="outOfServiceState", cond=doswitch() )
				}	 
				state("outOfServiceState") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name | Sistema BLOCCO: Out Of Service")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t215",targetState="handleRejectOutOfService",cond=whenRequest("loadrequest"))
				}	 
				state("handleRejectOutOfService") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("loadrequest(IOPORT_STATE)"), Term.createTerm("loadrequest(IOPORT_STATE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 
								                var CurrentHoldState = h.getHoldStateString()
								                var CauseStr = "'out_of_service'"
								answer("loadrequest", "retrylater", "retrylater($CauseStr,$CurrentHoldState)"   )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="outOfServiceState", cond=doswitch() )
				}	 
			}
		}
} 
