/* Generated by AN DISI Unibo */ 
package it.unibo.cargorobot

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Cargorobot ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		
		        var Slot     = 0
		        var X        = 0      // coordinate dello slot finale (arrivano dalla request)
		        var Y        = 0
		        var StepTime = 345
		
		        val XHOME = 0         // HOME
		        val YHOME = 0
		        val XIOP  = 4         // IOPort
		        val YIOP  = 0
		        val X5    = 2         // ingresso slot5 / marker
		        val Y5    = 5
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outcyan("$name | starting...")
						forward("setrobotstate", "setpos(0,0,down)" ,"robotsmart" ) 
						forward("setplanbuildelay", "value(0)" ,"robotsmart" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("idle") { //this:State
					action { //it:State
						CommUtils.outcyan("$name | waiting for a container...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="executeTransportIOPort",cond=whenRequest("transportContainer"))
				}	 
				state("executeTransportIOPort") { //this:State
					action { //it:State
						CommUtils.outcyan("$name | collecting container...")
						if( checkMsgContent( Term.createTerm("transportContainer(SLOT,TARGETX,TARGETY)"), Term.createTerm("transportContainer(SLOT,TARGETX,TARGETY)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
								                Slot = payloadArg(0).toInt()
								                X    = payloadArg(1).toInt()
								                Y    = payloadArg(2).toInt()
								request("moverobot", "moverobot($XIOP,$YIOP,$StepTime)" ,"robotsmart" )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t11",targetState="executeTransportSlot5",cond=whenReply("moverobotdone"))
					transition(edgeName="t12",targetState="finishKo",cond=whenReply("moverobotfailed"))
				}	 
				state("executeTransportSlot5") { //this:State
					action { //it:State
						CommUtils.outcyan("$name | deposit in slot5...")
						request("moverobot", "moverobot($X5,$Y5,$StepTime)" ,"robotsmart" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t23",targetState="marking",cond=whenReply("moverobotdone"))
					transition(edgeName="t24",targetState="finishKo",cond=whenReply("moverobotfailed"))
				}	 
				state("marking") { //this:State
					action { //it:State
						CommUtils.outcyan("$name | marker working...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_marking", 
				 	 					  scope, context!!, "local_tout_"+name+"_marking", 5000.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t35",targetState="executeTransport",cond=whenTimeout("local_tout_"+name+"_marking"))   
				}	 
				state("executeTransport") { //this:State
					action { //it:State
						CommUtils.outcyan("$name | moving to final slot")
						request("moverobot", "moverobot($X,$Y,$StepTime)" ,"robotsmart" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t46",targetState="backHome",cond=whenReply("moverobotdone"))
					transition(edgeName="t47",targetState="finishKo",cond=whenReply("moverobotfailed"))
				}	 
				state("backHome") { //this:State
					action { //it:State
						CommUtils.outcyan("$name | going back home")
						request("moverobot", "moverobot($XHOME,$YHOME,$StepTime)" ,"robotsmart" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t58",targetState="tuneHome",cond=whenReply("moverobotdone"))
					transition(edgeName="t59",targetState="finishKo",cond=whenReply("moverobotfailed"))
				}	 
				state("tuneHome") { //this:State
					action { //it:State
						request("tuneAtHome", "tuneAtHome(end)" ,"robotsmart" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t610",targetState="finishOk",cond=whenReply("tuneDone"))
				}	 
				state("finishOk") { //this:State
					action { //it:State
						CommUtils.outcyan("$name | trasporto finito con successo")
						answer("transportContainer", "transportDone", "transportDone($Slot)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("finishKo") { //this:State
					action { //it:State
						 val Cause = "fail_RobotSmart26"  
						CommUtils.outcyan("$name | trasporto fallito")
						answer("transportContainer", "transportFailed", "transportFailed($Cause)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
			}
		}
} 
