/* Generated by AN DISI Unibo */ 
package it.unibo.cargoservice

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Cargoservice ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		val h = cargoservice.Hold()
		
		        var CurrentReservedSlot = -1
		        var CurrentState        = "IDLE"
		        var IsOutOfService      = false
		        var Transporting        = false     // true mentre cargorobot sta trasportando
		        var OosMsg              = "'Guasto'"
		        var WaitStartTime       = 0L
		        var RemainingTime       = 30000L
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						delay(1000) 
						CommUtils.outmagenta("$name | avvio CargoService Core")
						 var ServiceWorking = "'WORKING'"  
						forward("updateWorkingState", "updateWorkingState($ServiceWorking)" ,"ioport" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("idle") { //this:State
					action { //it:State
						
						            CurrentState    = "IDLE"
						            Transporting    = false
						            var LedOff      = "'off'"
						            WaitStartTime   = 0L
						            RemainingTime   = 30000L
						CommUtils.outmagenta("$name | Sistema in stato IDLE")
						forward("led", "led($LedOff)" ,"ioport" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t016",targetState="handleLoadRequest",cond=whenRequest("loadrequest"))
					transition(edgeName="t017",targetState="handleOutOfService",cond=whenDispatch("outOfService"))
				}	 
				state("handleLoadRequest") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("loadrequest(IOPORT_STATE)"), Term.createTerm("loadrequest(IOPORT_STATE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
								                var IoportState = payloadArg(0).toBoolean()
								                var CurrentHoldState = h.getHoldStateString()
								
								                if (IoportState) {
								                    var SystemBusyStr = "'ioport_occupied'"
								answer("loadrequest", "retrylater", "retrylater($SystemBusyStr,$CurrentHoldState)"   )  
								CommUtils.outmagenta("$name | retrylater($SystemBusyStr, $CurrentHoldState)")
								
								                } else if (h.isFull()) {
								answer("loadrequest", "reject", "reject($CurrentHoldState)"   )  
								CommUtils.outmagenta("$name | reject($CurrentHoldState)")
								
								                } else {
								                    CurrentReservedSlot = h.reserveNextFreeSlot()
								                    if (CurrentReservedSlot != -1) {
								                        CurrentState = "ENGAGED"
								                        CurrentHoldState = h.getHoldStateString()
								                        var LedBlinking = "'blinking'"
								answer("loadrequest", "engaged", "engaged($CurrentReservedSlot,$CurrentHoldState)"   )  
								CommUtils.outmagenta("$name | engaged($CurrentReservedSlot, $CurrentHoldState)")
								forward("led", "led($LedBlinking)" ,"ioport" ) 
								
								                    } else {
								                        var SystemBusyStr = "'system_busy'"
								answer("loadrequest", "retrylater", "retrylater($SystemBusyStr,$CurrentHoldState)"   )  
								CommUtils.outmagenta("$name | retrylater($SystemBusyStr, $CurrentHoldState)")
								
								                    }
								                }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="engagedWaitContainer", cond=doswitchGuarded({ CurrentState == "ENGAGED"  
					}) )
					transition( edgeName="goto",targetState="idle", cond=doswitchGuarded({! ( CurrentState == "ENGAGED"  
					) }) )
				}	 
				state("engagedWaitContainer") { //this:State
					action { //it:State
						
						            if (WaitStartTime == 0L) {
						                WaitStartTime = System.currentTimeMillis()
						            }
						            var Elapsed = System.currentTimeMillis() - WaitStartTime
						            RemainingTime = 30000L - Elapsed
						            if (RemainingTime <= 0L) RemainingTime = 1L
						CommUtils.outmagenta("$name | In attesa del container (Tempo residuo: ${RemainingTime}ms)...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_engagedWaitContainer", 
				 	 					  scope, context!!, "local_tout_"+name+"_engagedWaitContainer", RemainingTime )  //OCT2023
					}	 	 
					 transition(edgeName="t118",targetState="handleTimeout",cond=whenTimeout("local_tout_"+name+"_engagedWaitContainer"))   
					transition(edgeName="t119",targetState="handleBusyRequest",cond=whenRequest("loadrequest"))
					transition(edgeName="t120",targetState="handleContainer",cond=whenDispatch("containerSensed"))
					transition(edgeName="t121",targetState="handleOutOfService",cond=whenDispatch("outOfService"))
				}	 
				state("handleBusyRequest") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("loadrequest(IOPORT_STATE)"), Term.createTerm("loadrequest(IOPORT_STATE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
								                var CurrentHoldState = h.getHoldStateString()
								                var SystemEngagedStr = "'system_engaged'"
								answer("loadrequest", "retrylater", "retrylater($SystemEngagedStr,$CurrentHoldState)"   )  
								CommUtils.outmagenta("$name | retrylater($SystemEngagedStr, $CurrentHoldState)")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitTransport", cond=doswitchGuarded({ Transporting  
					}) )
					transition( edgeName="goto",targetState="engagedWaitContainer", cond=doswitchGuarded({! ( Transporting  
					) }) )
				}	 
				state("handleTimeout") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name | TIMEOUT scaduto! Container non rilevato entro 30s.")
						
						            if (CurrentReservedSlot != -1) {
						                h.releaseSlot(CurrentReservedSlot)
						                CurrentReservedSlot = -1
						            }
						            var CurrentHoldState = h.getHoldStateString()
						            var StateStr = "'DISENGAGED'"
						            var TimeoutMsgStr = "'Timer scaduto (30s)'"
						forward("updateHoldDisplay", "updateHoldDisplay($StateStr,$CurrentHoldState,$TimeoutMsgStr)" ,"ioport" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("handleContainer") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name | Container rilevato -> movimento robot")
						
						            Transporting = true
						            var TargetX = h.getEntranceX(CurrentReservedSlot)
						            var TargetY = h.getEntranceY(CurrentReservedSlot)
						request("transportContainer", "transportContainer($CurrentReservedSlot,$TargetX,$TargetY)" ,"cargorobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitTransport", cond=doswitch() )
				}	 
				state("waitTransport") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name | In attesa della fine del trasporto...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t222",targetState="endTransport",cond=whenReply("transportDone"))
					transition(edgeName="t223",targetState="handleOutOfService",cond=whenReply("transportFailed"))
					transition(edgeName="t224",targetState="handleBusyRequest",cond=whenRequest("loadrequest"))
					transition(edgeName="t225",targetState="handleOutOfService",cond=whenDispatch("outOfService"))
				}	 
				state("endTransport") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name | Container portato nello slot definito")
						
						            h.setSlotOccupied(CurrentReservedSlot)
						            CurrentReservedSlot = -1
						            var CurrentHoldState = h.getHoldStateString()
						            var StateStr = "'LOADED'"
						            var LoadedMsgStr = "'Container preso in carico'"
						forward("updateHoldDisplay", "updateHoldDisplay($StateStr,$CurrentHoldState,$LoadedMsgStr)" ,"ioport" ) 
						delay(1500) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("handleOutOfService") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name | GUASTO RILEVATO: Sistema in Out Of Service")
						if( checkMsgContent( Term.createTerm("outOfService(CAUSE)"), Term.createTerm("outOfService(CAUSE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 OosMsg = "'Guasto sensore'"  
						}
						if( checkMsgContent( Term.createTerm("transportFailed(CAUSE)"), Term.createTerm("transportFailed(CAUSE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 OosMsg = "'Guasto robot'"  
						}
						
						            IsOutOfService = true
						
						            // Lo slot viene rilasciato solo se il robot NON sta trasportando
						            // (altrimenti il container potrebbe essere gia' nel robot)
						            if (!Transporting && CurrentReservedSlot != -1) {
						                h.releaseSlot(CurrentReservedSlot)
						                CurrentReservedSlot = -1
						            }
						
						            var CurrentHoldState = h.getHoldStateString()
						            var StateStr = "'OUT_OF_SERVICE'"
						            var LedRed = "'red'"
						forward("led", "led($LedRed)" ,"ioport" ) 
						forward("updateWorkingState", "updateWorkingState($StateStr)" ,"ioport" ) 
						forward("updateHoldDisplay", "updateHoldDisplay($StateStr,$CurrentHoldState,$OosMsg)" ,"ioport" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="outOfServiceState", cond=doswitch() )
				}	 
				state("outOfServiceState") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name | Sistema BLOCCATO: Out Of Service")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t326",targetState="handleRejectOutOfService",cond=whenRequest("loadrequest"))
				}	 
				state("handleRejectOutOfService") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("loadrequest(IOPORT_STATE)"), Term.createTerm("loadrequest(IOPORT_STATE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
								                var CurrentHoldState = h.getHoldStateString()
								                var CauseStr = "'out_of_service'"
								answer("loadrequest", "retrylater", "retrylater($CauseStr,$CurrentHoldState)"   )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="outOfServiceState", cond=doswitch() )
				}	 
			}
		}
} 
