/* Generated by AN DISI Unibo */ 
package it.unibo.cargorobot

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Cargorobot ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		
		    	var Slot = "slotX"
		    	var X = 0
		    	var Y = 0
		    	var StepTime = 10
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outcyan("$name | starting...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("idle") { //this:State
					action { //it:State
						CommUtils.outcyan("$name | waiting for a container...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t01",targetState="executeTransportSlot5",cond=whenRequest("transportContainer"))
				}	 
				state("executeTransportSlot5") { //this:State
					action { //it:State
						CommUtils.outcyan("$name | deposit in slot5")
						if( checkMsgContent( Term.createTerm("transportContainer(SLOT,TARGETX,TARGETY)"), Term.createTerm("transportContainer(SLOT,TARGETX,TARGETY)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
								    			Slot = payloadArg(0)
								    			X = payloadArg(1).toInt()
								    			Y = payloadArg(2).toInt()
								    			var X5 = 5
								    			var Y5 = 5
								request("moverobot", "moverobot($X5,$Y5,$StepTime)" ,"robotsmart_mock" )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t12",targetState="marking",cond=whenReply("moverobotdone"))
					transition(edgeName="t13",targetState="handleFinish",cond=whenReply("moverobotfailed"))
				}	 
				state("marking") { //this:State
					action { //it:State
						CommUtils.outcyan("$name | marker working...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_marking", 
				 	 					  scope, context!!, "local_tout_"+name+"_marking", 5000.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t24",targetState="executeTransport",cond=whenTimeout("local_tout_"+name+"_marking"))   
				}	 
				state("executeTransport") { //this:State
					action { //it:State
						CommUtils.outcyan("$name | moving to final slot")
						request("moverobot", "moverobot($X,$Y,$StepTime)" ,"robotsmart_mock" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t35",targetState="backHome",cond=whenReply("moverobotdone"))
					transition(edgeName="t36",targetState="handleFinish",cond=whenReply("moverobotfailed"))
				}	 
				state("backHome") { //this:State
					action { //it:State
						
						    		var XHOME = 0
						    		var YHOME = 0 	
						CommUtils.outcyan("$name | going back home")
						request("moverobot", "moverobot($XHOME,$YHOME,$StepTime)" ,"robotsmart_mock" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t47",targetState="handleFinish",cond=whenReply("moverobotdone"))
					transition(edgeName="t48",targetState="handleFinish",cond=whenReply("moverobotfailed"))
				}	 
				state("handleFinish") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("moverobotok(ARG)"), Term.createTerm("moverobotok(ARG)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outcyan("$name | trasporto finito con successo")
								answer("transportContainer", "transportDone", "transportDone($Slot)"   )  
						}
						if( checkMsgContent( Term.createTerm("moverobotfailed(PLANDONE,PLANTODO)"), Term.createTerm("moverobotfailed(PLANDONE,PLANTODO)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 var Cause = "fail_RobotSmart26"  
								CommUtils.outcyan("$name | trasporto fallito")
								answer("transportContainer", "transportFailed", "transportFailed($Cause)"   )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
			}
		}
} 
